apiVersion: v1
kind: Namespace
metadata:
  name: application

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
  namespace: application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: application-server
  template:
    metadata:
      labels:
        app: application-server
    spec:
      containers:
        - name: python-app
          image: 3anany/helloworld:vtag
          ports:
            - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: application-service
  namespace: application
spec:
  type: LoadBalancer
  selector:
    app: application-server
  ports:
    - port: 8000
      targetPort: 8000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  namespace: application
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: redis
          image: redis
          ports:
            - containerPort: 6379

---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: application
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: backend
