apiVersion: v1
kind: Namespace
metadata:
  name: application

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
  namespace: application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: application-server
  template:
    metadata:
      labels:
        app: application-server
    spec:
      containers:
        - name: python-app
          image: 3anany/helloworld:vtag
          ports:
            - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: application-service
  namespace: application
spec:
  type: LoadBalancer
  selector:
    app: application-server
  ports:
    - port: 5000
      targetPort: 5000
